export const models = [
    { value: 'gpt-4o', viewValue: 'GPT-4o (Default)' },
    { value: 'gpt-4o-mini', viewValue: 'GPT-4o Mini' },
    { value: 'o1', viewValue: 'O1' },
    { value: 'o1-mini', viewValue: 'O1 Mini' },
    { value: 'o1-pro', viewValue: 'O1 Pro' },
    { value: 'o3', viewValue: 'O3' },
    { value: 'o3-mini', viewValue: 'O3 Mini' },
    { value: 'o4-mini', viewValue: 'O4 Mini' },
    { value: 'gpt-4.1', viewValue: 'GPT-4.1' },
    { value: 'gpt-4.1-mini', viewValue: 'GPT-4.1 Mini' },
    { value: 'gpt-4.1-nano', viewValue: 'GPT-4.1 Nano' },
    { value: 'gpt-4.5-preview', viewValue: 'GPT-4.5 Preview' },
    { value: 'claude-3-7-sonnet', viewValue: 'Claude 3.7 Sonnet' },
    { value: 'claude-3-5-sonnet', viewValue: 'Claude 3.5 Sonnet' },
    { value: 'deepseek-chat', viewValue: 'DeepSeek Chat' },
    { value: 'deepseek-reasoner', viewValue: 'DeepSeek Reasoner' },
    { value: 'gemini-2.0-flash', viewValue: 'Gemini 2.0 Flash' },
    { value: 'gemini-1.5-flash', viewValue: 'Gemini 1.5 Flash' },
    { value: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo', viewValue: 'Meta-Llama 3.1 8B Instruct Turbo' },
    { value: 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo', viewValue: 'Meta-Llama 3.1 70B Instruct Turbo' },
    { value: 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo', viewValue: 'Meta-Llama 3.1 405B Instruct Turbo' },
    { value: 'mistral-large-latest', viewValue: 'Mistral Large Latest' },
    { value: 'pixtral-large-latest', viewValue: 'Pixtral Large Latest' },
    { value: 'codestral-latest', viewValue: 'Codestral Latest' },
    { value: 'google/gemma-2-27b-it', viewValue: 'Google Gemma 2 27B IT' },
    { value: 'grok-beta', viewValue: 'Grok Beta' }
];
